**dexing on ndarrays**

Basic indexing

Single element indexing

In [2]:
import numpy as np

In [3]:
x = np.arange(10)
x[2]

2

In [4]:
x[-2]

8

In [5]:
x.shape = (2, 5)
x[1, 3]

8

In [6]:
x[1, -1]

9

In [7]:
x[0]

array([0, 1, 2, 3, 4])

In [8]:
x[0][2]

2

Slicing and striding

In [3]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [4]:
x[-2:10]

array([8, 9])

In [5]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [6]:
x[5:]

array([5, 6, 7, 8, 9])

In [7]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape

(2, 3, 1)

In [8]:
x[1:2]

array([[[4],
        [5],
        [6]]])

Dimensional indexing tools

In [9]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [12]:
x[:, None, :, :].shape

(2, 1, 3, 1)

In [13]:
x = np.arange(5)
x[:, np.newaxis] + x[np.newaxis, :]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

Advanced indexing

Integer array indexing

In [14]:
x = np.arange(10, 1, -1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [15]:
x[np.array([3, 3, 1, 8])]

array([7, 7, 9, 2])

In [16]:
x[np.array([3, 3, -3, 8])]

array([7, 7, 4, 2])

In [17]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x[np.array([1, -1])]

array([[3, 4],
       [5, 6]])

In [19]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [20]:
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

In [21]:
y[np.array([0, 2, 4]), 1]

array([ 1, 15, 29])

In [22]:
y[np.array([0, 2, 4])]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [23]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [24]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]

array([[ 0,  2],
       [ 9, 11]])

In [25]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)
rows[:, np.newaxis]

array([[0],
       [3]], dtype=int64)

In [26]:
x[rows[:, np.newaxis], columns]

array([[ 0,  2],
       [ 9, 11]])

In [27]:
x[np.ix_(rows, columns)]

array([[ 0,  2],
       [ 9, 11]])

In [28]:
x[rows, columns]

array([ 0, 11])

Boolean array indexing

In [29]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

In [30]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20
x

array([ 1., 19., 18.,  3.])

In [31]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b[:, 5]

array([False, False, False,  True,  True])

In [32]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [33]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [34]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = (x.sum(-1) % 2) == 0
rows

array([False,  True, False,  True])

In [35]:
columns = [0, 2]
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

In [36]:
rows = rows.nonzero()[0]
x[rows[:, np.newaxis], columns]

array([[ 3,  5],
       [ 9, 11]])

In [37]:
x = np.arange(30).reshape(2, 3, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [38]:
b = np.array([[True, True, False], [False, True, True]])
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

Combining advanced and basic indexing

In [39]:
y = np.arange(35).reshape(5,7)
y[np.array([0, 2, 4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [40]:
y[:, 1:3][np.array([0, 2, 4]), :]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [41]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x[1:2, 1:3]

array([[4, 5]])

In [42]:
x[1:2, [1, 2]]

array([[4, 5]])

In [43]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [44]:
x[b[:, 5], 1:3]

array([[22, 23],
       [29, 30]])

Field access

In [45]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
x['a'].shape

(2, 2)

In [46]:
x['a'].dtype

dtype('int32')

In [47]:
x['b'].shape

(2, 2, 3, 3)

In [48]:
x['b'].dtype

dtype('float64')

Assigning values to indexed arrays

In [50]:
x = np.arange(10)
x[2:7] = 1

In [51]:
x[2:7] = np.arange(5)

In [52]:
x[1] = 1.2
x[1]

1

In [53]:
x = np.arange(0, 50, 10)
x

array([ 0, 10, 20, 30, 40])

In [54]:
x[np.array([1, 1, 3, 1])] += 1
x

array([ 0, 11, 20, 31, 40])

Dealing with variable numbers of indices within programs

In [55]:
z = np.arange(81).reshape(3, 3, 3, 3)
indices = (1, 1, 1, 1)
z[indices]

40

In [56]:
indices = (1, 1, 1, slice(0, 2))
z[indices]

array([39, 40])

In [57]:
indices = (1, Ellipsis, 1)
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [58]:
z[[1, 1, 1, 1]]

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [59]:
z[(1, 1, 1, 1)]

40