**Data types**

Array types and conversions between types

In [1]:
import numpy as np

In [2]:
x = np.float32(1.0)
x

1.0

In [3]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [4]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [5]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

In [6]:
z.astype(float)                 

array([0., 1., 2.])

In [7]:
np.int8(z)

array([0, 1, 2], dtype=int8)

In [8]:
z.dtype

dtype('uint8')

In [9]:
d = np.dtype(int)
d

dtype('int32')

In [10]:
np.issubdtype(d, np.integer)

True

In [11]:
np.issubdtype(d, np.floating)

False

Overflow Errors

In [12]:
np.power(100, 8, dtype=np.int64)

10000000000000000

In [13]:
np.power(100, 8, dtype=np.int32)

1874919424

In [14]:
np.iinfo(int)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [15]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [16]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)