**Universal functions (ufunc) basics**

In [1]:
import numpy as np

In [2]:
np.array([0,2,3,4]) + np.array([1,1,-1,2])

array([1, 3, 2, 6])

Ufunc methods

In [3]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.add.reduce(x, 1)

array([ 3, 12, 21])

In [5]:
np.add.reduce(x, (0, 1))

36

In [6]:
x.dtype

dtype('int32')

In [7]:
np.multiply.reduce(x, dtype=float)

array([ 0., 28., 80.])

In [8]:
y = np.zeros(3, dtype=int)
y

array([0, 0, 0])

In [9]:
np.multiply.reduce(x, dtype=float, out=y)

array([ 0, 28, 80])

Type casting rules

In [10]:
mark = {False: ' -', True: ' Y'}
def print_table(ntypes):
    print('X ' + ' '.join(ntypes))
    for row in ntypes:
        print(row, end='')
        for col in ntypes:
            print(mark[np.can_cast(row, col)], end='')
        print()
print_table(np.typecodes['All'])

X ? b h i l q p B H I L Q P e f d g F D G S U V O M m
? Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
b - Y Y Y Y Y Y - - - - - - Y Y Y Y Y Y Y Y Y Y Y - Y
h - - Y Y Y Y Y - - - - - - - Y Y Y Y Y Y Y Y Y Y - Y
i - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
l - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
q - - - - - Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
p - - - - - Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
B - - Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
H - - - Y Y Y Y - Y Y Y Y Y - Y Y Y Y Y Y Y Y Y Y - Y
I - - - - - Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
L - - - - - Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
Q - - - - - - - - - - - Y Y - - Y Y - Y Y Y Y Y Y - -
P - - - - - - - - - - - Y Y - - Y Y - Y Y Y Y Y Y - -
e - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y Y - -
f - - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y - -
d - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
g - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
F - - - - - - - - - - - - - 