**cpies and views**


Indexing operations

In [2]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
y = x[1:3]  # creates a view
y

array([1, 2])

In [5]:
x[1:3] = [10, 11]
x

array([ 0, 10, 11,  3,  4,  5,  6,  7,  8,  9])

In [6]:
y

array([10, 11])

In [7]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
y = x[[1, 2]]
y

array([[3, 4, 5],
       [6, 7, 8]])

In [9]:
y.base is None

True

In [10]:
x[[1, 2]] = [[10, 11, 12], [13, 14, 15]]
x

array([[ 0,  1,  2],
       [10, 11, 12],
       [13, 14, 15]])

In [11]:
y

array([[3, 4, 5],
       [6, 7, 8]])

Other operations

In [12]:
x = np.ones((2, 3))
y = x.T  # makes the array non-contiguous
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
z = y.view()
z.shape = 6

AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.

view or a copy

In [14]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
y = x.reshape(3, 3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
y.base  # .reshape() creates a view

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
z = y[[2, 1]]
z

array([[6, 7, 8],
       [3, 4, 5]])

In [18]:
z.base is None  # advanced indexing creates a copy

True