**Interoperability with NumPy**


Using arbitrary objects in NumPy

In [29]:
import numpy as np

In [2]:
x = np.array([1, 2, 5.0, 8])
x.__array_interface__

{'data': (2258015243136, False),
 'strides': None,
 'descr': [('', '<f8')],
 'typestr': '<f8',
 'shape': (4,),
 'version': 3}

In [3]:
class wrapper():
    pass
arr = np.array([1, 2, 3, 4])
buf = arr.__array_interface__
buf

{'data': (2258014254960, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (4,),
 'version': 3}

In [4]:
buf['shape'] = (2, 2)
w = wrapper()
w.__array_interface__ = buf
new_arr = np.array(w, copy=False)
new_arr

array([[1, 2],
       [3, 4]])

In [5]:
new_arr[0, 0] = 1000
new_arr

array([[1000,    2],
       [   3,    4]])

In [6]:
arr

array([1000,    2,    3,    4])

Operating on foreign objects without converting

In [7]:
def f(x):
    return np.mean(np.exp(x))

In [8]:
x = np.array([1, 2, 3, 4])
f(x)

21.1977562209304

Interoperability examples

Pandas Series objects

In [9]:
import pandas as pd
ser = pd.Series([1, 2, 3, 4])
type(ser)

pandas.core.series.Series

In [10]:
np.exp(ser)

0     2.718282
1     7.389056
2    20.085537
3    54.598150
dtype: float64

In [11]:
np.sin(ser)

0    0.841471
1    0.909297
2    0.141120
3   -0.756802
dtype: float64

In [12]:
np.add(ser, np.array([5, 6, 7, 8]))

0     6
1     8
2    10
3    12
dtype: int64

In [13]:
f(ser)

21.1977562209304

In [14]:
result = ser.__array__()
type(result)

numpy.ndarray

PyTorch tensors

In [22]:
import torch
data = [[1, 2],[3, 4]]
x_np = np.array(data)
x_tensor = torch.tensor(data)
x_np

array([[1, 2],
       [3, 4]])

In [23]:
x_tensor

tensor([[1, 2],
        [3, 4]])

In [24]:
np.exp(x_tensor)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5982]], dtype=torch.float64)

In [25]:
import torch
t = torch.arange(4)
np.abs(t)

tensor([0, 1, 2, 3])

CuPy arrays

In [30]:
import cupy as cp
x_gpu = cp.array([1, 2, 3, 4])
np.mean(np.exp(x_gpu))

ModuleNotFoundError: No module named 'cupy'