NumPy Basic

In [2]:
import numpy as np

In [1]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(a[0])

[1 2 3 4]


Basic Array

In [7]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.ones(2)

array([1., 1.])

In [10]:
np.empty(2) 

array([1., 1.])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

Adding, removing, and sorting elements

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Shape and Size of an array

In [6]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [7]:
array_example.size

24

In [8]:
array_example.shape

(3, 2, 4)

Reshape an array

In [9]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [10]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [11]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

convert a 1D array into a 2D array

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [13]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [14]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [15]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [17]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [18]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)