**NumPy Basic**

In [1]:
import numpy as np

In [1]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(a[0])

[1 2 3 4]


**Basic Array**

In [7]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.ones(2)

array([1., 1.])

In [10]:
np.empty(2) 

array([1., 1.])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

**Adding, removing, and sorting elements**

In [3]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

**Shape and Size of an array**

In [6]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [7]:
array_example.size

24

In [8]:
array_example.shape

(3, 2, 4)

**Reshape an array**

In [9]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [10]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [11]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

**convert a 1D array into a 2D array**

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [13]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [14]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [15]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [17]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [18]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

**Indexing and slicing**


In [3]:
data = np.array([1, 2, 3])
data[1]

2

In [4]:
data[0:2]

array([1, 2])

In [5]:
data[1:]

array([2, 3])

In [6]:
data[-2:]

array([2, 3])

In [7]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [8]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [9]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [11]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [12]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [14]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [15]:
print(a[b])

[1 2 3 4]


In [16]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


**create an array from existing data**

In [2]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [4]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [5]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [6]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [7]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [9]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [10]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [11]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
b2 = a.copy()

In [13]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Basic array operations**

In [14]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [15]:
data - ones

array([0, 1])

In [16]:
data * data

array([1, 4])

In [17]:
data / data

array([1., 1.])

In [18]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [19]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [20]:
b.sum(axis=1)

array([2, 4])

**Broadcasting**

In [3]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

**Useful array operations**

In [4]:
data.max()

2.0

In [5]:
data.min()

1.0

In [6]:
data.sum()

3.0

In [7]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [8]:
a.sum()

4.8595784

In [9]:
a.min()

0.05093587

In [10]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

**Creating matrices**

In [11]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
data[0, 1]

2

In [13]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [14]:
data[0:2, 0]

array([1, 3])

In [15]:
data.max()

6

In [16]:
data.min()

1

In [17]:
data.sum()

21

In [18]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [19]:
data.max(axis=0)

array([5, 6])

In [20]:
data.max(axis=1)

array([2, 5, 6])

In [21]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [22]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [23]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
rng = np.random.default_rng()
rng.random(3)

array([0.51541779, 0.71067368, 0.98004409])

In [27]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
rng.random((3, 2)) 

array([[0.70833363, 0.18785134],
       [0.02985458, 0.97092747],
       [0.99016535, 0.54592687]])

**Generating random numbers**


In [30]:
rng.integers(5, size=(2, 4))

array([[2, 2, 1, 4],
       [4, 2, 4, 4]], dtype=int64)

**get unique items and counts**

In [31]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [32]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [33]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [34]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
print(indices)

[0 1 2]


In [38]:
print(occurrence_count)

[2 1 1]


**Transposing and reshaping a matrix**


In [39]:
data.reshape(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

**Reverse an array**

Reversing a 1D array

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
reversed_arr = np.flip(arr)

In [4]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


Reversing a 2D array

In [5]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [6]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [7]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [8]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


**Reshaping and flattening multidimensional arrays**


In [9]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


**Docstring**

In [14]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [15]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method


In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
a?

Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        c:\users\yepco\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-

In [17]:
def double(a):
  '''Return a * 2'''
  return a * 2

In [18]:
double?

Signature: double(a)
Docstring: Return a * 2
File:      c:\users\yepco\appdata\local\temp\ipykernel_13536\3639010673.py
Type:      function


In [19]:
double??

Signature: double(a)
Source:   
def double(a):
  '''Return a * 2'''
  return a * 2
File:      c:\users\yepco\appdata\local\temp\ipykernel_13536\3639010673.py
Type:      function


In [20]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method


In [21]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method
