NumPy Basic

In [1]:
import numpy as np
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(a[0])

[1 2 3 4]


In [7]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [8]:
np.zeros(2)

array([0., 0.])

In [9]:
np.ones(2)

array([1., 1.])

In [10]:
np.empty(2) 

array([1., 1.])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)